version: '3.7'
services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgresql-data:/var/lib/postgresql/data
  app:
    build: .
    tty: true
    volumes:
      - .:/gadget_app
    ports:
      - "3000:3000"
    environment:
      RDS_HOSTNAME: db
      RDS_USERNAME: postgres
volumes:
  postgresql-data:
    driver: local
